# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            niuware
tagline:          ''
description:      ''
url:              https://niuware.github.io
baseurl:          /

author:
  name:           'niuware'
  url:            https://niuware.github.io

github:           https://github.com/niuware
  repo:           https://github.com/niuware/niuware.github.io

exclude:          [ Gemfile, Gemfile.lock, LICENSE.md, README.md ]
